MemberCentre/urls.py
from django.urls import path,include
from MemberCentre import views
app_name='MemberCentre'
urlpatterns = [
    #http://localhost:8000/index/
    path('index/<str:account>', views.index,name='index'),
    path('index_delete/<str:account>', views.index_delete,name='index_delete'),
    path('create/', views.create,name='create'),
    path('space/<str:account>', views.space,name='space'),
    path('update/<str:account>', views.update,name='update'),
    path('delete/<str:account>', views.delete,name='delete'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('forget/', views.forget,name='forget'),
    path('grade/', views.grade,name='grade'),
    path('grade_forget/', views.grade_forget,name='grade_forget'),
] 

aicoco/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
    path('trastrasim/', include('trastrasim.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('MemberCentre/',include('MemberCentre.urls')),
    path('consultant/',include('consultant.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

root/urls.py
from django.urls import path
from . import views

app_name = "root"

urlpatterns = [
    path('', views.index, name="index"),
    path('__empty/', views.empty, name="__empty"),
]

MemberCentre/models.py
from django.db import models

# Create your models here.
class MemberCentre(models.Model):
    account = models.CharField(max_length=45)
    password = models.CharField(max_length=45)
    name = models.CharField(max_length=45, blank=True, null=True)
    cellphone = models.CharField(max_length=45, blank=True, null=True)
    email = models.CharField(max_length=45)
    birth = models.DateField()
    address = models.CharField(max_length=45, blank=True, null=True)
    gender = models.CharField(max_length=45, blank=True, null=True)
    education = models.CharField(max_length=45, blank=True, null=True)
    job = models.CharField(max_length=45, blank=True, null=True)
    grade = models.CharField(max_length=45)
    vcode = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'membercentre'

MemberCentre/views.py
##########################################################################################################################
##  
##  目前問題:
##      1.  同意條款及政策未實作
##      2.  會員修改資料未驗證(生日、姓名、目前職業、地址、手機號碼)
##      3.  刪除會員資料,應二次確認(管理員、會員)
##  
##  說明文件:  
##      1.index() => 管理員的空間
##      2.index_delete() => 管理員刪除會員
##      3.space() => 會員的空間
##      4.create() => 建立會員帳號
##      5.grade() => 驗證會員信箱
##      6.grade_forget() => 補寄驗證碼
##      7.update() => 會員與管理員更改會員資料
##      8.delete() => 會員刪除帳戶
##      9.login() => 會員與管理員登入
##      10.logout() => 會員與管理員登出
##      11.random_code() => 隨機驗證碼/密碼
##      12.send_email() => 寄送email
##      13.forget() => 忘記密碼
##      14.google_captcha() =>Google機器人api驗證
##
##
##########################################################################################################################


from django.shortcuts import render,redirect
from .models import MemberCentre
from django.http import HttpResponse
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.conf import settings
import datetime
import random
import smtplib
import json
import urllib





#管理員空間
def index(request,account):
    members = MemberCentre.objects.all()
    return render(request,'MemberCentre/index.html',locals())


#管理員刪除帳號
def index_delete(requset,account):
    member = MemberCentre.objects.get(account=str(account))
    member.delete()
    response = HttpResponse("<script>alert('刪除成功');location.href='/MemberCentre/index/aicoco'</script>")
    return response



#會員個人空間
def space(request,account):
    member = MemberCentre.objects.get(account=str(account))
    return render(request,'MemberCentre/space.html',locals())



#創建會員帳號
def create(request): 
    if request.method == "POST":
        #將接收到的值丟進相應變數
        account = request.POST["account"]
        email = request.POST["email"]
        password = request.POST["password"]
        password2 = request.POST["password2"]
        birth = request.POST["birth"]
        agree = request.POST["agree"]
        grade = "未驗證會員"
        #調用google_captcha()google回傳user是否為機器人
        gcaptcha = request.POST.get('g-recaptcha-response')
        result = google_captcha(gcaptcha)
        #比對資料庫帳號和email是否重複
        account_filter = MemberCentre.objects.filter(account = account)
        email_filter = MemberCentre.objects.filter(email = email)
        if len(account_filter)>0 : 
            return HttpResponse("<script>alert('帳號已有人使用,請重新輸入');location.href='/MemberCentre/create'</script>")
        elif len(email_filter)>0 :  
            return HttpResponse("<script>alert('email已註冊過,請重新輸入');location.href='/MemberCentre/create'</script>")  
        #驗證密碼是否輸入正確
        elif password != password2 or len(password) < 6 :
            return HttpResponse("<script>alert('密碼不得小於六位數或是比對不符,請重新輸入');location.href='/MemberCentre/create'</script>")
        #生日不得為空值
        elif birth =="":
            return HttpResponse("<script>alert('請選取生日');location.href='/MemberCentre/create'</script>")
        #是否同意條款及政策
        elif agree != "checked" :
            return HttpResponse("<script>alert('請勾選同意條款及政策');location.href='/MemberCentre/create'</script>")
        #判定用戶是否為機器人
        elif result == False :
            return HttpResponse("<script>alert('未通過機器人驗證');location.href='/MemberCentre/create'</script>")
        else :
            #產生亂數驗證碼
            tpassword = random_code()
            whoscall = "驗證碼"
            #執行寄送驗證email
            send_email(tpassword,email,whoscall,account)
            #將資料寫進DB
            MemberCentre.objects.create(account = account, email = email, password = password, birth = birth, grade = grade,vcode = tpassword)
            response = HttpResponse("<script>alert('帳號已新增,驗證碼已寄送信箱,請重新登入後進會員空間驗證');location.href='/MemberCentre/grade'</script>")
            #刪除已登入cookie,讓user重新登入
            response.delete_cookie("account")
            return response 
    return render(request,'MemberCentre/create.html',locals())



#驗證會員信箱
def grade(request) :
    if request.method == "POST":
        #將接收到的值丟進相應變數
        user_email = request.POST["email"]
        user_account = request.POST["account"]
        user_vcode = request.POST["vcode"]
        #filter過濾器比對email和account
        member = MemberCentre.objects.filter(account=user_account,email=user_email)
        if member :
            members = MemberCentre.objects.get(account=str(user_account))
            #比對驗證碼是否相符
            if members.vcode == user_vcode :
                members.grade = "已驗證會員"
                members.save()
                return HttpResponse("<script>alert('信箱驗證成功');location.href='/MemberCentre/login/'</script>")
            else :
                return HttpResponse("<script>alert('驗證失敗,請重新輸入');location.href='/MemberCentre/grade/'</script>")
        else :
            return HttpResponse("<script>alert('帳號或email輸入錯誤,請重新輸入');location.href='/MemberCentre/grade/'</script>")
    return render(request,'MemberCentre/grade.html',locals())



#補寄驗證碼
def grade_forget(request) :
    if request.method == "POST":
        #將接收到的值丟進相應變數
        user_email = request.POST["email"]
        user_account = request.POST["account"]
        member = MemberCentre.objects.filter(account=user_account,email=user_email)
        if member :
            members = MemberCentre.objects.get(account=str(user_account))
            #亂數編碼
            tpassword = random_code()
            #將亂數編碼寫進DB更新舊的驗證碼
            account = members.account
            email = members.email
            members.vcode = tpassword
            members.save()
            whoscall = "驗證碼"  
            #執行寄email密碼的動作
            send_email(tpassword,email,whoscall,account)
            return HttpResponse("<script>alert('新驗證碼已寄出');location.href='/MemberCentre/grade/'</script>")
        else :
            return HttpResponse("<script>alert('帳號或email輸入錯誤,請重新輸入');location.href='/MemberCentre/grade_forget'</script>")
    return render(request,'MemberCentre/grade_forget.html',locals())



#管理員或會員修改個人資料
def update(request,account): 
    if request.method == "POST":
        #將接收到的值丟進相應變數
        # account = request.POST["account"] => 帳號不准修改
        # email = request.POST["email"] =>email 不准修改
        password = request.POST["password"]
        name = request.POST["name"]
        cellphone = request.POST["cellphone"]
        # birth = request.POST["birth"]  => 生日也不准修改
        address = request.POST["address"]
        gender = request.POST["gender"]
        education = request.POST["education"]
        job = request.POST["job"]
        member = MemberCentre.objects.get(account=str(account))
        #驗證用戶修改的資料
        if password =="" or len(password) < 6 :  
            return HttpResponse("<script>alert('密碼不得為空且不得小於6位數');location.href='/MemberCentre/update/{}'</script>".format(account)) 
        else :
            #修改資料庫中的會員資料,並儲存
            # member.account = account
            member.password = password
            # member.email = email
            member.name = name
            member.cellphone = cellphone
            # member.birth = birth
            member.address = address
            member.gender = gender
            member.education = education
            member.job = job
            member.save()
            return HttpResponse("<script>alert('帳號修改成功');location.href='/MemberCentre/space/{}'</script>".format(account))
    member = MemberCentre.objects.get(account=str(account))
    return render(request,'MemberCentre/update.html',locals())



#會員刪除資料
def delete(request,account): 
    member = MemberCentre.objects.get(account=str(account))
    #刪除DB會員資料
    member.delete()
    response = HttpResponse("<script>alert('刪除成功');location.href='/MemberCentre/create'</script>")
    #刪除會員cookie
    response.delete_cookie("account")
    return response



#google機器人驗證
def google_captcha(gcaptcha) :
    url = 'https://www.google.com/recaptcha/api/siteverify'
    values = {'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,'response': gcaptcha}
    data = urllib.parse.urlencode(values).encode()
    req =  urllib.request.Request(url, data=data)
    response = urllib.request.urlopen(req)
    result = json.loads(response.read().decode())
    atlast = result['success']
    return atlast



#管理員或會員登入
def login(request):  
    if request.method == "POST":
        account = request.POST['account']
        password = request.POST['password']
        rememberme = request.POST['rememberme']
        #調用google_captcha(gcaptcha)回傳user是否為機器人
        gcaptcha = request.POST.get('g-recaptcha-response')
        result = google_captcha(gcaptcha)
        #過濾器方法filter比對輸入帳號和密碼是否相符，並取得資料表中account的欄位值
        member = MemberCentre.objects.filter(account=account,password=password).values("account")
        if member :
            members = MemberCentre.objects.get(account=str(account))
            usergrade = members.grade
        #驗證user是否為機器人和已通過驗證
        if member and (usergrade =="管理員" or usergrade =="已驗證會員") and result == True :
            response = HttpResponse("<script>alert('登入成功');location.href='/'</script>")
            #讓user選擇cookie過期時間
            onehour = datetime.datetime.now()+datetime.timedelta(seconds=60)
            onedate = datetime.datetime.now()+datetime.timedelta(days=1)
            oneweek = datetime.datetime.now()+datetime.timedelta(days=7)
            onemonth = datetime.datetime.now()+datetime.timedelta(days=30)
            if rememberme == 'nostore' :
                response.set_cookie("account",member[0]["account"])
            elif rememberme == 'onehour' :
                response.set_cookie("account",member[0]["account"],expires=onehour)
            elif rememberme == 'onedate' :
                response.set_cookie("account",member[0]["account"],expires=onedate)
            elif rememberme == 'oneweek' :
                response.set_cookie("account",member[0]["account"],expires=oneweek)
            elif rememberme == 'onemonth' :

MemberCentre/templates/MemberCentre/create.html
{% extends 'base.html'%} {% block content %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<body class="">
    <div class="page">
        <div class="page-single">
            <div class="container">
                <div class="row">
                    <div class="col col-login mx-auto">
                        <div class="text-center mb-6">
                            <img src="./assets/brand/tabler.svg" class="h-6" alt="">
                        </div>
                        <form class="card" action="" method="post">
                            {% csrf_token %}
                            <div class="card-body p-5">
                                <div class="card-title">建立帳戶</div>
                                <div class="form-group">
                                    <label class="form-label">帳號</label>
                                    <input type="text" name="account" class="form-control" placeholder="請輸入帳號" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">密碼(最少需六位數)</label>
                                    <input type="password" name="password" class="form-control" placeholder="請輸入密碼" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">確認密碼(最少需六位數)</label>
                                    <input type="password" name="password2" class="form-control" placeholder="請輸入密碼" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">電子郵件</label>
                                    <input type="email" name="email" class="form-control" placeholder="Enter email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$">   
                                    <!-- /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/ -->
                                </div>
                                <div class="form-group">
                                    <label class="form-label">生日</label>
                                    <input type="date" name="birth" class="form-control" placeholder="生日" required>
                                </div>
                                <div class="form-group">
                                    <label class="custom-control custom-checkbox">
                                        <input type="radio" name="agree" value="checked" class="custom-control-input">
                                        <span class="custom-control-label">同意
                                            <a href="#">條款及政策</a>
                                        </span>
                                        <input type="radio" name="agree" value="unchecked" class="custom-control-input" checked style="display:none" />
                                    </label>
                                </div>
                                <div class="g-recaptcha" data-sitekey="6Lc7UF0UAAAAACunvp51ysIPUWB32Uo0YzHcRLKX" data-theme=""></div>
                                <div class="form-footer">
                                    <button type="submit" class="btn btn-primary btn-block">建立帳號</button>
                                </div>
                            </div>
                        </form>
                        <div class="text-center text-muted">
                            已有帳號?
                            <a href="{% url 'MemberCentre:login' %}">登入</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

MemberCentre/templates/MemberCentre/forget.html
{% extends 'base.html'%} {% block content %}

<body class="">
  <div class="page">
    <div class="page-single">
      <div class="container">
        <div class="row">
          <div class="col col-login mx-auto">
            <div class="text-center mb-6">
              <img src="./assets/brand/tabler.svg" class="h-6" alt="">
            </div>
            <form class="card" action="" method="POST">
              {% csrf_token %}
              <div class="card-body p-6">
                <div class="card-title">重置您的密碼</div>
                <div class="form-group">
                  <label class="form-label">帳號</label>
                  <input type="text" name="account" class="form-control" placeholder="輸入您的帳號">
                </div>
                <div class="form-group">
                  <label class="form-label">email</label>
                  <input type="email" name="email" class="form-control" placeholder="輸入您的email">
                </div>
                
                <div class="form-footer">
                  <button type="submit" class="btn btn-primary btn-block">發送密碼到email</button>
                </div>
              </div>
            </form>
            <div class="text-center text-muted">
             一不小心又想起密碼了?
              <a href="{% url 'MemberCentre:login' %}">登入</a>
            </div>
            <div class="text-center text-muted">
              沒有帳號?
              <a href="{% url 'MemberCentre:create' %}">建立帳號</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

MemberCentre/templates/MemberCentre/grade.html
{% extends 'base.html'%} {% block content %}

<body class="">
    <div class="page">
        <div class="page-single">
            <div class="container">
                <div class="row">
                    <div class="col col-login mx-auto">
                        <div class="text-center mb-6">
                            <img src="./assets/brand/tabler.svg" class="h-6" alt="">
                        </div>
                        <form class="card" action="" method="post">
                            {% csrf_token %}
                            <div class="card-body p-6">
                                <div class="card-title">驗證您的帳號</div>
                                <div class="form-group">
                                    <label class="form-label">請輸入email</label>
                                    <input type="text" name="email" class="form-control" placeholder="請輸入電子信箱" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">請輸入帳號</label>
                                    <input type="text" name="account" class="form-control" placeholder="請輸入帳號" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">請輸入驗證碼</label>
                                    <input type="text" name="vcode" class="form-control" placeholder="請輸入驗證碼" required>
                                </div>

                                <div class="form-footer">
                                    <button type="submit" class="btn btn-primary btn-block">核對驗證碼</button>
                                </div>
                            </div>
                        </form>
                        <div class="text-center text-muted">
                            沒收到驗證碼?
                            <a href="{% url 'MemberCentre:grade_forget' %}">補寄驗證碼</a>
                        </div>
                        <div class="text-center text-muted">
                            沒有帳號?
                            <a href="{% url 'MemberCentre:create' %}">申請帳號</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

MemberCentre/templates/MemberCentre/grade_forget.html
{% extends 'base.html'%} {% block content %}

<body class="">
    <div class="page">
        <div class="page-single">
            <div class="container">
                <div class="row">
                    <div class="col col-login mx-auto">
                        <div class="text-center mb-6">
                            <img src="./assets/brand/tabler.svg" class="h-6" alt="">
                        </div>
                        <form class="card" action="" method="post">
                            {% csrf_token %}
                            <div class="card-body p-6">
                                <div class="card-title">補寄驗證碼</div>
                                <div class="form-group">
                                    <label class="form-label">請輸入email</label>
                                    <input type="text" name="email" class="form-control" placeholder="請輸入電子信箱" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">請輸入帳號</label>
                                    <input type="text" name="account" class="form-control" placeholder="請輸入帳號" required>
                                </div>
                                <div class="form-footer">
                                    <button type="submit" class="btn btn-primary btn-block">寄送驗證碼</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

MemberCentre/templates/MemberCentre/index.html
<!-- 此為管理帳密頁面 -->
{% extends 'base.html'%} {% block content %}
<a href="{% url 'MemberCentre:create' %}" class="btn btn-primary mb-3">
    <i class="fa fa-plus-circle" aria-hidden="true"></i> 會員新增</a>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>帳號</th>
            <th>密碼</th>
            <th>姓名</th>
            <th>電話</th>
            <th>郵件</th>
            <th>生日</th>
            <th>會員狀態</th>
        </tr>
    </thead>
    <tbody>
        <!-- 用for迴圈將views.py定義的members依欄位顯示(隱藏password) -->
        {% for member in members %}
        <tr>
            <td>{{ member.id }}</td>
            <td>{{ member.account }}</td>
            <td>{{ member.password }}</td>
            <td>{{ member.name }}</td>
            <td>{{ member.cellphone }}</td>
            <td>{{ member.email }}</td>
            <td>{{ member.birth }}</td>
            <td>{{ member.grade }}</td>
            <td>
                <!-- 修改按鈕會導向update的url因為在url表定義後面必須加上int才會使用views的update方法,所以
                後面必須加上這個項目欄位的id -->
                {% if member.account != 'aicoco' %}
                <a href="{% url 'MemberCentre:update' member.account %}" class="btn btn-info mr-2">修改</a>
                <!-- 刪除同修改原理 -->
                <a href="{% url 'MemberCentre:index_delete' member.account %}" class="btn btn-danger">刪除</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

MemberCentre/templates/MemberCentre/login.html
{% extends 'base.html'%} {% block content %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<body class="">
  <div class="page">
    <div class="page-single">
      <div class="container">
        <div class="row">
          <div class="col col-login mx-auto">
            <div class="text-center mb-6">
              <img src="./assets/brand/tabler.svg" class="h-6" alt="">
            </div>
            <form class="card" action="" method="POST">
              {% csrf_token %}
              <div class="card-body p-5">
                <div class="card-title">帳戶登入</div>
                <div class="form-group">
                  <label class="form-label">帳號</label>
                  <input type="text" name="account" class="form-control" placeholder="Enter account">
                </div>
                <div class="form-group">
                  <label class="form-label">密碼</label>
                  <input type="password" name="password" class="form-control" placeholder="Password">
                </div>
                <div class="form-group">
                  <label class="form-label">
                    <font style="vertical-align: inherit;">選擇登入時間</font>
                  </label>
                  <select class="form-control custom-select" name="rememberme">
                    <option value="nostore" selected="selected">
                      <font style="vertical-align: inherit;">不儲存</font>
                    </option>
                    <option value="onehour">
                      <font style="vertical-align: inherit;">一小時</font>
                    </option>
                    <option value="oneday">
                      <font style="vertical-align: inherit;">一天</font>
                    </option>
                    <option value="oneweek">
                      <font style="vertical-align: inherit;">七天</font>
                    </option>
                    <option value="onemonth">
                      <font style="vertical-align: inherit;">一個月</font>
                    </option>
                  </select>
                </div>
                <div class="g-recaptcha" data-sitekey="6Lc7UF0UAAAAACunvp51ysIPUWB32Uo0YzHcRLKX" data-theme=""></div>
                <div class="form-footer">
                  <button type="submit" class="btn btn-primary btn-block">登入</button>
                </div>
              </div>
            </form>
            <div class="text-center text-muted">
              <a href="{% url 'MemberCentre:forget' %}">忘記密碼</a>
            </div>
            <div class="text-center text-muted">
              沒有帳號?
              <a href="{% url 'MemberCentre:create' %}">建立帳號</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

MemberCentre/templates/MemberCentre/space.html
<!-- 此為管理帳密頁面 -->
{% extends 'base.html'%} {% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                <form class="card">
                    <div class="card-body">
                        <h3 class="card-title">會員空間</h3>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label">帳號</label>
                                    <input type="text" class="form-control" disabled="" placeholder="帳號" value="{{member.account}}">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label">密碼</label>
                                    <input type="password" class="form-control" disabled="" placeholder="密碼" value="{{member.password}}">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label">姓名</label>
                                    <input type="text" class="form-control" disabled="" placeholder="姓名" value="{{member.name}}">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <label class="form-label">電子郵件</label>
                                    <input type="email" class="form-control" disabled="" placeholder="email" value="{{member.email}}">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <label class="form-label">手機號碼</label>
                                    <input type="text" class="form-control" disabled="" placeholder="手機號碼" value="{{member.cellphone}}">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <label class="form-label">目前職業</label>
                                    <input type="text" class="form-control" disabled="" placeholder="職業" value="{{member.job}}">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="form-label">地址</label>
                                    <input type="text" class="form-control" disabled="" placeholder="地址" value="{{member.address}}">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <label class="form-label">生日</label>
                                    <input type="text" class="form-control" disabled="" placeholder="生日" value="{{member.birth}}">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <label class="form-label">性別</label>
                                    <input type="text" class="form-control" disabled="" placeholder="性別" value="{{member.gender}}">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-label">教育程度</label>
                                    <input type="text" class="form-control" disabled="" placeholder="教育程度" value="{{member.education}}">
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4">
                                <div class="form-group">
                                    <label class="form-label">會員狀態</label>
                                    <input type="text" class="form-control" name="grade" value="{{member.grade}}" disabled="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'MemberCentre:update' request.COOKIES.account %}" class="btn btn-info mr-2">修改個人資料</a>
                    </div>
                </form>
            </h1>
        </div>
    </div>
</div>
{% endblock %}