aicoco/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
    path('trastrasim/', include('trastrasim.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('MemberCentre/',include('MemberCentre.urls')),
    path('consultant/',include('consultant.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

consultant/consultant/urls.py
from django.urls import path
from . import views
app_name='consultant'
urlpatterns = [
    path('', views.index,name='index'),
    path('create/', views.create,name='create'),
    path('update/<int:id>', views.update,name='update'),
    path('delete/<int:id>', views.delete,name='delete'),
]

consultant/urls.py
from django.urls import path
from . import views
app_name='consultant'
urlpatterns = [
    path('', views.index,name='index'),
    path('create/', views.create,name='create'),
    path('update/<int:id>', views.update,name='update'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('complete/<int:id>', views.complete,name='complete'),
]

root/urls.py
from django.urls import path
from . import views

app_name = "root"

urlpatterns = [
    path('', views.index, name="index"),
    path('__empty/', views.empty, name="__empty"),
]

consultant/consultant/models.py
from django.db import models

# Create your models here.

class Consultant(models.Model):
    姓名 = models.CharField(max_length=20,null=False)
    學歷 = models.CharField(max_length=100,null=False)
    經歷 = models.CharField(max_length=100,null=False)
    證照 = models.CharField(max_length=100,null=False)
    
    class Meta:
        db_table = "consultants"

consultant/models.py
from django.db import models

# Create your models here.

# class Consultant(models.Model):
#     姓名 = models.CharField(max_length=20,null=False)
#     學歷 = models.CharField(max_length=100,null=False)
#     經歷 = models.CharField(max_length=100,null=False)
#     證照 = models.CharField(max_length=100,null=False)
    
#     class Meta:
#         db_table = "consultants"

class Consultant(models.Model):
    姓名 = models.CharField(max_length=20)
    學歷 = models.CharField(max_length=100)
    經歷 = models.CharField(max_length=100)
    證照 = models.CharField(max_length=100)
    image = models.CharField(max_length=45, blank=True, null=True)
    操盤特色 = models.CharField(max_length=500)
    url = models.CharField(max_length=100)
    
    class Meta:
        managed = False
        db_table = 'consultants'

consultant/consultant/views.py
from django.shortcuts import render,redirect
from .models import Consultant
from django.http import HttpResponse
import datetime

# Create your views here.
def index(request):  
    
    title = "投顧老師"

    #todo 讀取顧問資料傳給index.html
    consultants = Consultant.objects.all()
    # print(list(consultants))

    return render(request,'consultant/index.html',locals())

def create(request):
    if request.method == 'POST':
        姓名 = request.POST["姓名"]
        學歷 = request.POST["學歷"]
        經歷 = request.POST["經歷"]
        證照 = request.POST["證照"]

        #todo 接收到的顧問資料寫進資料庫
        Consultant.objects.create(姓名=姓名,學歷=學歷,經歷=經歷,證照=證照)
        
        #todo 新增完成後轉到http://localhost:8000/consultant
        return redirect("/consultant")
       
    title = "會員新增" 
    return render(request,'consultant/create.html',locals())

def update(request,id):
    if request.method == 'POST':        
        姓名 = request.POST["姓名"] 
        學歷 = request.POST["學歷"]      
        經歷 = request.POST["經歷"]
        證照 = request.POST["證照"]

        #todo 修改資料庫中的顧問資料
        consultant = Consultant.objects.get(id=int(id))
        consultant.姓名 = 姓名
        consultant.學歷 = 學歷
        consultant.經歷  = 經歷
        consultant.證照 = 證照
        consultant.save()
        
        #todo 修改完成後轉到http://localhost:8000/consultant
        return redirect('/consultant')

    title = "會員修改"

    #todo 根據會員編號取得會員資料傳給update.html
    consultant = Consultant.objects.get(id=int(id))
    return render(request,'consultant/update.html',locals())

def delete(request,id):
    #todo 根據會員編號刪除會員資料
    consultant = Consultant.objects.get(id=int(id))
    consultant.delete()

    #todo 刪除完成後轉到http://localhost:8000/consultant
    return redirect('/consultant')

consultant/views.py
from django.shortcuts import render,redirect
from .models import Consultant
from django.http import HttpResponse
import datetime
from django.core.files.storage import FileSystemStorage

# Create your views here.
def index(request):  
    
    # title = "投顧老師"
    #todo 讀取顧問資料傳給complete.html
    consultants = Consultant.objects.all()
    # print(list(consultants))
    
    return render(request,'consultant/index.html',locals())

def create(request):
    consultants = Consultant.objects.all()
    if request.method == "POST" and request.FILES["image"]:
        myfile = request.FILES['image']
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)
        # title="檔案上傳"
    # if request.method == 'POST':
        姓名 = request.POST["姓名"]
        學歷 = request.POST["學歷"]
        經歷 = request.POST["經歷"]
        證照 = request.POST["證照"]
        image = myfile.name

        #todo 接收到的顧問資料寫進資料庫
        Consultant.objects.create(姓名=姓名,學歷=學歷,經歷=經歷,證照=證照,image=image)
        
        #todo 新增完成後轉到http://localhost:8000/consultant
        return redirect("/consultant")
       
    # title = "新增" 
    return render(request,'consultant/create.html',locals())

def update(request,id):
    if request.method == "POST" and request.FILES["image"]:
        myfile = request.FILES['image']
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)
        # title="檔案上傳"
    # if request.method == 'POST':        
        姓名 = request.POST["姓名"] 
        學歷 = request.POST["學歷"]      
        經歷 = request.POST["經歷"]
        證照 = request.POST["證照"]
        image = myfile.name

        #修改資料庫中的顧問資料
        consultant = Consultant.objects.get(id=int(id))
        consultant.姓名 = 姓名
        consultant.學歷 = 學歷
        consultant.經歷  = 經歷
        consultant.證照 = 證照
        consultant.image = image
        consultant.save()
        print(consultant.經歷)
        
        #修改完成後轉到http://localhost:8000/consultant
        return redirect('/consultant')

    # title = "修改"

    #根據顧問編號取得顧問資料傳給update.html
    consultant = Consultant.objects.get(id=int(id))
    return render(request,'consultant/update.html',locals())

def delete(request,id):
    #todo 根據顧問編號刪除顧問資料
    consultant = Consultant.objects.get(id=int(id))
    consultant.delete()

    #刪除完成後轉到http://localhost:8000/consultant
    return redirect('/consultant')

def complete(request, id):  
    #todo 讀取顧問資料傳給complete.html
    dates = Consultant.objects.get(id=int(id))
    # print(dates)
    # print(consultant)
   

    
    return render(request,'consultant/complete.html',locals())

consultant/templates/consultant/complete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <div class="col-md-6 col-xl6">
                <div class="card">
                    <img class="card-img-top" src="/media/{{dates.image}}" width="10%" alt="And this isn't my nose. This is a false one.">
                    <div class="card-header">
                        <div class="avatar avatar-md mr-3" style="background-image: url(/media/{{dates.image}})"></div>
                        <h3 class="card-title">{{dates.姓名}} 顧問</h3>
                    </div>
                    <div class="alert alert-primary" role="alert">
                        <h4>經歷：{{dates.經歷}}</h4>
                    </div>
                    <div class="alert alert-warning" role="alert">
                        <h4>學歷：{{dates.學歷}}</h4>
                    </div>
                    <div class="alert alert-danger" role="alert">
                        <h4>證照：{{dates.證照}}</h4>
                    </div>
                    <div class="card-footer">
                        <a href="{{dates.url}}" title="推薦影音">推薦影音I</a>
                        <a href="#" title="推薦影音">推薦影音II</a>
                        <a href="#" title="推薦影音">推薦影音III</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xl6">                                
                <img src="/static/images/1.jpg"><h2 style="text-align: center">操盤特色</h2>
                <div class="alert alert-danger">{{dates.操盤特色}}</div>
                <div><em style="font-weight: bolder">聯絡方式</em></div><img src="/static/images/line.jpg">
            </div>
            <div class="col-md-2 col-xl6">
                <div style="border: 3px solid royalblue">
                    <h3 style="text-align: center">廣告</h3>
                    <img src="/static/images/1.gif" alt="廣告">
                    <img src="/static/images/1.gif" alt="廣告">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block scripts %} {% endblock %}

consultant/templates/consultant/create.html
{% extends 'base.html'%} {% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            {% for consultant in consultants%}
            <div class="col-md-6 col-xl-4">
                <div class="card">
                    <div class="card-status bg-blue"></div>
                    <div class="card-header">
                        <div class="avatar avatar-md mr-3" style="background-image: url(/media/{{consultant.image}})"></div>
                        <h3 class="card-title">{{consultant.姓名}} 顧問</h3>
                        <!-- <div class="card-options">
                            <a href="#" class="card-options-collapse" data-toggle="card-collapse">
                                <i class="fe fe-chevron-up"></i>
                            </a>
                        </div> -->
                    </div>
                    <div class="card-body">
                        經歷：{{consultant.經歷}}
                    </div>
                    <div class="card-footer">
                        學歷：{{consultant.學歷}}
                    </div>
                </div>
                <div>
                    <a href="{% url 'consultant:update' consultant.id  %}" class="btn btn-secondary">
                        <i class="fas fa-pencil-alt">修改</i>
                    </a>
                    <a href="{% url 'consultant:delete' consultant.id  %}" class="btn btn-danger">
                        <i class="fas fa-trash-alt">刪除</i>
                    </a>
                </div>
            </div>
            {% endfor %}
            <div class="container">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="姓名" class="col-sm-2 col-form-label">姓名</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="姓名" id="姓名" placeholder="姓名">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="學歷" class="col-sm-2 col-form-label">學歷</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="學歷" id="學歷" placeholder="學歷">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="經歷" class="col-sm-2 col-form-label">經歷</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="經歷" id="經歷" placeholder="經歷">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="證照" class="col-sm-2 col-form-label">證照</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="證照" id="證照" placeholder="證照">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="image" class="col-sm-2 col-form-label col-form-label-lg">大頭照</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control form-control-lg" name="image" id="image">
                        </div>
                    </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10 offset-md-2">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-bath" aria-hidden="true"></i>新增</button>
            </div>
        </div>
        </form>
    </div>
</div>
{% endblock %}

consultant/templates/consultant/index.html
{% extends 'base.html' %} {% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">                
            {% for consultant in consultants%}
            <div class="col-md-6 col-xl-4">
                <div class="card">                    
                    <a href="{% url 'consultant:complete' consultant.id %}">
                        <img class="card-img-top" src="/media/{{consultant.image}}" width="10%" alt="And this isn't my nose. This is a false one.">
                    </a>
                    <div class="card-header">
                        <div class="avatar avatar-md mr-3" style="background-image: url(/media/{{consultant.image}})"></div>
                        <h3 class="card-title">{{consultant.姓名}} 顧問</h3>
                        <div class="card-options">
                            <a href="#" class="card-options-collapse" data-toggle="card-collapse">
                                <i class="fe fe-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        經歷：{{consultant.經歷}}
                    </div>
                    <div class="card-body">
                        學歷：{{consultant.學歷}}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

consultant/templates/consultant/update.html
{% extends 'base.html'%} {% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="姓名" class="col-sm-2 col-form-label">姓名</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="姓名" id="姓名" placeholder="姓名" value={{consultant.姓名}}>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="學歷" class="col-sm-2 col-form-label">學歷</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="學歷" id="學歷" placeholder="學歷" value={{consultant.學歷}}>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="經歷" class="col-sm-2 col-form-label">經歷</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="經歷" id="經歷" placeholder="經歷" value={{consultant.經歷}}>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="證照" class="col-sm-2 col-form-label">證照</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="證照" id="證照" placeholder="證照" value={{consultant.證照}}>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="image" class="col-sm-2 col-form-label col-form-label-lg">大頭照</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control form-control-lg" name="image" id="image">
                    </div>
                </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10 offset-md-2">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-bath" aria-hidden="true"></i> 修改</button>
            </div>
        </div>
        </form>
    </div>
</div>
</div>
{% endblock %}