aicoco/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('root.urls')),
    path('trastrasim/', include('trastrasim.urls')),
    path('portfolio/',include('portfolio.urls')),
    path('MemberCentre/',include('MemberCentre.urls')),
    path('consultant/',include('consultant.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

root/urls.py
from django.urls import path
from . import views

app_name = "root"

urlpatterns = [
    path('', views.index, name="index"),
    path('__empty/', views.empty, name="__empty"),
]

trastrasim/urls.py
from django.urls import path
from . import views

app_name='trastrasim'
urlpatterns = [
    path('', views.index,name='index'),
    path('compinfo/', views.company_info,name='companyinfo'),
    path('sc/<int:id>', views.strategy_choice,name='strategychoice'),     
    path('cu/', views.company_info_update,name='companyupdate'),
    path('du/', views.stocks_price_update,name='dailyupdate'),    
]

trastrasim/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class COMP(models.Model):
    CompanyID = models.IntegerField(db_column='CompanyID', primary_key=True)      
    CompanyName = models.CharField(db_column='CompanyName', max_length=20)     
    Abbreviation = models.CharField(db_column='Abbreviation', max_length=10, blank=True, null=True)
       
    class Meta:
        db_table = "companies_of_tw50"
        # managed= True

class STPR(models.Model):
    CompanyID = models.ForeignKey(COMP, models.DO_NOTHING, db_column='CompanyID', primary_key=True)  # Field name made lowercase.
    Date = models.CharField(db_column='Date', max_length=20)  # Field name made lowercase.
    TradingVolume = models.CharField(db_column='TradingVolume', max_length=20)  # Field name made lowercase.
    TurnOverinvalue = models.CharField(db_column='TurnOverinvalue', max_length=20)  # Field name made lowercase.
    OpeningPrice = models.CharField(db_column='OpeningPrice', max_length=20)  # Field name made lowercase.
    HighestPrice = models.CharField(db_column='HighestPrice', max_length=20)  # Field name made lowercase.
    LowestPrice = models.CharField(db_column='LowestPrice', max_length=20)  # Field name made lowercase.
    ClosingPrice = models.CharField(db_column='ClosingPrice', max_length=20)  # Field name made lowercase.
    PriceDifference = models.CharField(db_column='PriceDifference', max_length=20)  # Field name made lowercase.
    NumberofTransactions = models.CharField(db_column='NumberofTransactions', max_length=20)  # Field name made lowercase.

    class Meta:
        # managed = True
        db_table = 'stocksprices_of_tw50'
        unique_together = (('CompanyID', 'Date'),)

trastrasim/views.py
from django.shortcuts import render, redirect
from .models import COMP, STPR
from .modelSim import Simulator
from . import companyinfo
import pyquery, requests, time, re, os, json

# Create your views here.
def index(request):
    title = "StockP"
    if request.method == "POST":
        StockTicker = request.POST['StockTicker']
        comps = COMP.objects.all()
        datas = STPR.objects.all()
        st = comps[int(StockTicker)-1].CompanyID
  
    return render(request, 'trastrasim/index.html', locals())


def company_info(request):
    title = "Company Infomations"
    comps= COMP.objects.exclude(CompanyID__in= [2311, 2325, 3697])      
    datas= STPR.objects.all()    
    # for comp in comps:
    #     datas= STPR.objects.filter(CompanyID= comp.CompanyID)     
    if request.method == 'POST':
        compid= int(request.POST['tickerNumber']    )
        comps= COMP.objects.filter(CompanyID__icontains=compid)  
        datas= STPR.objects.filter(CompanyID__CompanyID__icontains=compid, Date__icontains= '107/06/01')           
        # rows= zip([comps,], [datas,])
        rows= zip([comp for comp in comps], [data for data in datas])
        return render(request, 'trastrasim/comps.html', locals())    
           
    rows= zip([comp for comp in comps], [data for data in datas.filter(Date__icontains= '107/06/01')])

    return render(request, 'trastrasim/comps.html', locals())    


def strategy_choice(request,id):
    title= "StockS"
    comp= COMP.objects.get(CompanyID=id)
    datas= STPR.objects.filter(CompanyID=id, Date__icontains= '107/')
    Simulator(datas).showchart()
    if request.method =="POST":
        choice= request.POST['StockChoice']
        net= strategy(choice,id)
        netBC= round(net[0],2)*1000
        buy= net[1]
        buyP= net[2]
        costC= net[3]
        sell= net[4]
        sellP= net[5]
        benefit= net[6]
        benesum= net[7]
        cont= net[8]
        contl= net[9]
        rows= zip(cont,buy,buyP,sell,sellP,benefit,benesum)
        # scripts= net[7]
        # div= net[8]
        netBCR= round(netBC/1000/costC*100,2)
        netBcrPY= round(((1+netBCR/100)**(1/30)-1)*12*100,2)
        comp= COMP.objects.get(CompanyID=id)        
        return render(request,'trastrasim/strategy.html',locals())
        
    return render(request,'trastrasim/strategychoice.html',locals())

def strategy(choice,id):
    title= "Strategy"
    datas= STPR.objects.filter(CompanyID=id)
    
    if choice == '1':
        net= Simulator(datas).strategy1()
   
    if choice == '2':
        net= Simulator(datas).strategy2()

    if choice == '3':
        net= Simulator(datas).strategy3()

    return net

def stocks_price_update(request):
    comps= COMP.objects.all()
    for comp in comps:
        for year in range(2016,2019):
            for month in range(1,13):
                stockNo= comp.CompanyID
                print('stockNo: {}'.format(stockNo))               
                zero= '0' if month < 10 else ''   
                date= '{}{}{}01'.format(year,zero,month)           
                dbase= STPR.objects.filter(CompanyID= stockNo, Date__iregex= r'{}/0*{}/[0-9]+'.format(year-1911,month))  

                if not dbase:  
                    print("Requesting")
                    url= 'http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date={}&stockNo={}'.format(date,stockNo)       
                    response= requests.get(url)
                    time.sleep(3)
                    print('Date: {}'.format(date))
                    if response.status_code == 200:
                        datas= json.loads(response.text)           
                        print(datas['stat'])

                        if datas['stat'] == "OK":  
                            for row in range(len(datas['data'])):
                                    STPR.objects.create(CompanyID= COMP.objects.get(CompanyID= stockNo), Date= datas['data'][row][0],TradingVolume= datas['data'][row][1], TurnOverinvalue= datas['data'][row][2], OpeningPrice= datas['data'][row][3], HighestPrice= datas['data'][row][4], LowestPrice= datas['data'][row][5],ClosingPrice= datas['data'][row][6], PriceDifference= datas['data'][row][7], NumberofTransactions= datas['data'][row][8])
                            print('Done')
                        
                        else:
                            print("No Data")

                else:
                    print("Read already")

    return redirect('/trastrasim')


def company_info_update(request):    
    a= companyinfo.Companies()
    a.update()        
        
    return redirect('/trastrasim')
    

trastrasim/templates/trastrasim/__empty.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="my-3 my-md-5">
  <div class="container">
    <div class="page-header">
      <h1 class="page-title">
        AICOCO空白頁面
      </h1>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
{% endblock %}

trastrasim/templates/trastrasim/comps.html
{% extends 'base.html' %}{% block content %}

<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="col">
                    <h1 class="page-title">
                        Companies Infomations
                    </h1>
                </div>
                <div class="col">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-5">

                                <label for="tickerN" class="sr-only">Ticker Number</label>
                                <input type="text" class="form-control" id="tickerNumber" placeholder="搜尋代碼" name="tickerNumber">
                            </div>

                            <div class="col">

                                <button type="submit" class="btn btn-primary mb-2">Search</button>
                            </div>
                            <div class="col">
                                <a class="btn btn-primary mb-2" href="{% url 'trastrasim:companyinfo' %}" role="button">
                                    Reset</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>CompanyID</th>
                    <th>CompanyName</th>
                    <th>成交股數</th>
                    <th>成交金額</th>
                    <th>收盤價</th>
                    <th>成交筆數</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                {% for row in rows %}
                <tr>
                    <td>{{row.0.CompanyID}}</td>
                    <td>{{row.0.CompanyName}}</td>
                    <td>{{row.1.TradingVolume}}</td>
                    <td>{{row.1.TurnOverinvalue}}</td>
                    <td>{{row.1.ClosingPrice}}</td>
                    <td>{{row.1.NumberofTransactions}}</td>
                    <td>
                        <a class="btn btn-light" href="{% url 'trastrasim:strategychoice' row.0.CompanyID %}" role="button">
                            <i class="fas fa-arrow-circle-right" style="color:maroon;"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %} {% block scripts %} {% endblock %}

trastrasim/templates/trastrasim/index.html
{% extends 'base.html' %}{% block content %}

<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">

            </h1>

        </div>

        {% for comp in comps %} {% if comp.CompanyID == st %}
        <h2>{{comp.CompanyName}}</h2>
        {% endif %} {% endfor %}

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-sm-4"></div>
                <label for="StockTicker" class="col-sm-2 col-form-label text-right">Stock Ticker</label>
                <div class="col-sm-5">
                    <select class="form-control" id="StockTicker" name="StockTicker">
                        <option value="0">Select</option>
                        <option value="1">TSMC</option>
                        <option value="2">FOXC</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary col-sm-1">Search</button>
            </div>

        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>TradingVolume</th>
                    <th>TurnOverinvalue</th>
                    <th>OpeningPrice</th>
                    <th>Highestprice</th>
                    <th>Lowestprice</th>
                    <th>Closingprice</th>
                    <th>Pricedifference</th>
                    <th>NumberofTransactions</th>
                </tr>
            </thead>
            <!-- Date,TradingVolume,TurnOverinvalue,OpeningPrice,Highestprice,Lowestprice,Closingprice,Pricedifference,NumberofTransactions, -->
            <tbody>
                {% for data in datas %}
                <tr>
                    <td>{{data.Date}}</td>
                    <td>{{data.TradingVolume}}</td>
                    <td>{{data.TurnOverinvalue}}</td>
                    <td>{{data.OpeningPrice}}</td>
                    <td>{{data.HighestPrice}}</td>
                    <td>{{data.LowestPrice}}</td>
                    <td>{{data.ClosingPrice}}</td>
                    <td>{{data.PriceDifference}}</td>
                    <td>{{data.NumberofTransactions}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %} {% block scripts %} {% endblock %}

trastrasim/templates/trastrasim/strategy.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">      
       
        </div>
        <div class="row">
        <hr>

        <div class="col">
        <h2>{{comp.CompanyName}}</h2>  
        <h5>{{comp.CompanyID}}</h5>
        <span><i class="fas fa-cubes"></i> Info.</span>
        </div>

        <div class="col"> 
            <h5>${{netBC}}</h5>
            <h7>獲利</h7>
        </div>
       
        <div class="col"> 
            <h5>{{netBCR}}%</h5>
            <h7>獲利率</h7>
        </div>
       
        <div class="col"> 
            <h5>{{contl}}</h5>
            <h7>交易次數</h7>
        </div>

        <div class="col"> 
            <h5>{{netBcrPY}}%</h5>
            <h7>年化報酬率</h7>
        </div>

        <div class="col" style="text-align: right">
            <a class="btn btn-outline-dark" href="{% url 'trastrasim:companyinfo' %}" role="button">
            <i class="fas fa-chart-pie"></i> 回策略中心</a> </a>  
            <!-- <hr> -->
            <a class="btn btn-outline-dark" href="#" role="button" onclick="history.back()">
            <i class="fas fa-arrow-alt-circle-left"></i> Last Page</a>
        </div>
     
        <hr>
        </div>
        {% include 'out2.html' %}    
        <table class="table">
            <thead>
                <tr>
                    <th>第幾筆交易</th>
                    <th>購買日期</th>
                    <th>購買價格</th>
                    <th>出售日期</th>
                    <th>出售價格</th>
                    <th>淨利/每筆交易</th>
                    <th>淨利(累積總額)</th>
                    <th> </th>
                    <th></th>
                </tr>
            </thead>
    
            <tbody>
                {% for row in rows %}
                <tr>
                    <td>{{row.0}}</td>
                    <td>{{row.1}}</td>
                    <td>{{row.2}}</td>   
                    <td>{{row.3}}</td>
                    <td>{{row.4}}</td>
                    <td>{{row.5}}</td>
                    <td>{{row.6}}</td>
                    <td><i class="fas fa-check-circle" style="color:greenyellow;"></i>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>  
    </div>
</div>
{% endblock %} {% block scripts %}
<script src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.16.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.16.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.16.min.js"></script> {% endblock %}

trastrasim/templates/trastrasim/strategychoice.html
{% extends 'base.html' %}{% load static %}
{% block content %}

<div class="my-3 my-md-5">
    <div class="container">
        <a class="btn btn-outline-dark" href="{% url 'trastrasim:companyinfo' %}" role="button">
            <i class="fas fa-arrow-alt-circle-left"></i> Last Page</a>

        <hr>

        <h2>{{comp.CompanyName}}</h2>
        <h5>{{comp.CompanyID}}</h5>

        <hr>

        <div class="card-group">
            <div class="card">
                <img class="card-img-top" src="{% static 'images/barupdn.png' %}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">BarUpDown</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content
                        is a little bit longer.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Defaul Strategy</small>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="{% static 'images/smileface.png' %}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Smailing Face</h5>
                    <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Defaul Strategy</small>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="{% static 'images/Consecutive-Down-Days-Trading-Winning-Example.png' %}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">consecutive up/down</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card
                        has even longer content than the first to show that equal height action.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Defaul Strategy</small>
                </div>
            </div>
        </div>

        <hr>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <div class="row">
                    <div class="col">
                <label for="StockChoice" class="col col-form-label text-right">Strategy Choice</label>
                    </div>
                <div class="col">
                    <select class="form-control" id="StockChoice" name="StockChoice">
                        <option value="0">Select</option>
                        <option value="1">BarUpDown</option>
                        <option value="2">Smiling Face</option>
                        <option value="3">Consecutive Up/Down</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-outline-primary col-sm-2">Search</button>
                </div>
            </div>

        </form>
        {% include 'out.html' %}    

        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>TradingVolume</th>
                    <th>TurnOverinvalue</th>
                    <th>OpeningPrice</th>
                    <th>Highestprice</th>
                    <th>Lowestprice</th>
                    <th>Closingprice</th>
                    <th>Pricedifference</th>
                    <th>NumberofTransactions</th>
                </tr>
            </thead>
            <!-- Date,TradingVolume,TurnOverinvalue,OpeningPrice,Highestprice,Lowestprice,Closingprice,Pricedifference,NumberofTransactions, -->
            <tbody>
                {% for data in datas %}
                <tr>
                    <td>{{data.Date}}</td>
                    <td>{{data.TradingVolume}}</td>
                    <td>{{data.TurnOverinvalue}}</td>
                    <td>{{data.OpeningPrice}}</td>
                    <td>{{data.HighestPrice}}</td>
                    <td>{{data.LowestPrice}}</td>
                    <td>{{data.ClosingPrice}}</td>
                    <td>{{data.PriceDifference}}</td>
                    <td>{{data.NumberofTransactions}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %} {% block scripts %} {% endblock %}